# Generated by Django 5.2.15 on 2026-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='time',
            new_name='created',
        ),
        migrations.AddField(
            model_name='listing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
