# Generated by Django 5.2.15 on 2026-07-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_bid_price_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
