# Generated by Django 5.2.15 on 2026-07-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_time_listing_created_listing_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='updated',
        ),
    ]
